---


- name: mysql server
  hosts: db1 #remplace par le serveur sur lequel on veut executer le playbook
  tasks:
  - name: update repository
    apt:
      update_cache: yes

  - name: Install MariaDB server package
    apt: 
      name: mariadb-server 
      state: present

  - name: Create `/root/.my.cnf`  with root password credentials
    template:
      src:  my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600
  - name: Start Mysql Service
    service: 
      name: mysql 
      state: started 
      enabled: true
  
  - name: Install python-pymysql package #required for mysql_db tasks
    apt: 
      name: python-pymysql 
      state: present 

  - name: Ensure mysql root password is updated for all root accounts
    mysql_user:
      name: root
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: ansible
      priv: '*.*:ALL,GRANT'
      check_implicit_admin: true
    
  - name: Create a new database
    mysql_db: 
      name: ajc
      login_unix_socket: /var/run/mysqld/mysqld.sock 
      state: present 
      collation: utf8_general_ci

  - name: Create a database user
    mysql_user: 
      name: ajc
      password: ansible 
      login_unix_socket: /var/run/mysqld/mysqld.sock
      priv: 'ansibleTest.*:ALL' 
      host: '%' 
      state: present
  
  - name: copy data file 
    copy:
      src: ./dump.sql
      dest: /tmp/dump.sql

  - name: insert data into database
    mysql_db:
      name: ajc
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: import
      target: /tmp/dump.sql
